### ISSUE TITLE
Using cl_image_tag to drive transformations

### ISSUE THREAD

**Issue by johanandre** [0sc/activestorage-cloudinary-service#5]
I've been using Cloudinary for a number of projects and feel quite good about using Cloudinarys helper (cl_image_tag) to crop, face-detect, grayscale and transform images "on-the-fly". Is there a possibility to do this with Active storage or am I stuck with using the variant-functionality?

**Comment by 0sc** [comment]
Hey @johanandre, lemme look into this and get to you.

**Comment by dmerand** [comment]
I can definitely second how excellent it would be to have `cl_image_tag` available via ActiveStorage. For me a big point of using Cloudinary is getting these kinds of transformations as I need them, versus having to use ImageMagick etc. on my server. It would be handy to be able to grab those transformations via the Rails [transform api](http://api.rubyonrails.org/v5.2.0/classes/ActiveStorage/Variant.html) if possible (or have a workaround to use it while still doing ActiveStorage).

Thanks!

**Comment by dmerand** [comment]
Just to follow up, there is one way to use Cloudinary tranformations that seems to work on some of my test data. You can use the [blob.key](http://edgeapi.rubyonrails.org/classes/ActiveStorage/Blob.html#method-i-key) syntax to get the Cloudinary key to use for transformations as you regularly would using the Cloudinary gem.

Say you have a model object `person` and your `ActiveStorage` attached file is `headshot`, uploaded through this Cloudinary service. Your view code for a 100x100px resize might look like this:

```
<%= cl_image_tag(@person.headshot.key, width: 100, height: 100, crop: :pad) %>
```

I'm not sure how kosher this is, because it's quite different from the auto-generated URL that you get using `blob.service_url`, but it works decently well for my use case.

**Comment by 0sc** [comment]
Yup, what @dmerand said. As of now, activestorage transformation processor wouldn't natively support cloudinary transformations.

As an alternative to @dmerand suggestion above, you can also consider setting up an [upload preset](https://support.cloudinary.com/hc/en-us/articles/360004967272-Upload-Preset-Configuration) with your desired transformations if this will apply for every image uploaded.

Monkey patching `ActiveStorage::Variant` is another option, but there's pain down that road.

**Comment by 0sc** [comment]
There's the ongoing discussion #7 on possible specifying upload transformations as part of the configurations. If that falls through, will be another option
